// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCRm5CA-3Ly3PJNPsk8YrAIb_BTakm8nA',
    appId: '1:438399986882:web:5dd9c0bb37682acb8adf5b',
    messagingSenderId: '438399986882',
    projectId: 'yanana-8de3b',
    authDomain: 'yanana-8de3b.firebaseapp.com',
    storageBucket: 'yanana-8de3b.appspot.com',
    measurementId: 'G-EEF2N21EQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxWDsN0mISVhtxecgAaP6jp6LDbcXu1pU',
    appId: '1:438399986882:android:2383ac1fa494930c8adf5b',
    messagingSenderId: '438399986882',
    projectId: 'yanana-8de3b',
    storageBucket: 'yanana-8de3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjGfqF5oSSwlr4wRva9YjZ92Z_-uMJE80',
    appId: '1:438399986882:ios:a1817731b6cb6d518adf5b',
    messagingSenderId: '438399986882',
    projectId: 'yanana-8de3b',
    storageBucket: 'yanana-8de3b.appspot.com',
    iosBundleId: 'com.example.yanana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjGfqF5oSSwlr4wRva9YjZ92Z_-uMJE80',
    appId: '1:438399986882:ios:b9446e64bbdbf9478adf5b',
    messagingSenderId: '438399986882',
    projectId: 'yanana-8de3b',
    storageBucket: 'yanana-8de3b.appspot.com',
    iosBundleId: 'com.example.yanana.RunnerTests',
  );
}
